export const SEED_CATALOG = {
  heroImage:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuB5eBWOoUHGFdrCwFyEmjnc2BQ9yZkSqmmqKhCVE964iXus240YFcWvTKVhGZMTqcrla0gDoXTlmw0zQ-YIUFtILOLCmvW5x-TqCn3ESpuVpgJPURsKmnIIBSN5NtIkJrSyq7p-EQzvsd4orMOPDbI9I8YYEaBGvM3o-aAdvecSY3_9c7C0AQW4KtDxqASuRs3BTbDSWFj3RtY7WZfGPOffE2QMIt8E0TcN4ZtDRHEEcdPMmu5jE-IOYZHcAl3FGhiAUIOpNbe8Ut9N',
  products: [
    {
      id: '1',
      name: 'Силовой удлинитель ProConnect 50м на катушке',
      nameEn: 'ProConnect 50m Power Extension Reel',
      price: 3190,
      oldPrice: 4250,
      image:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuCC9w0tezE_2Jgc1KJNMhMCmwGCFZbF98gjkxDD7lMArZwG4bGNml3y445GLQNRVscfgr45m2YodAgAuCvN2qL6jo_DHFgoV_TpvKB5arZ3F-F79Zcduimccrc4HjwV7HyduA9U-KUmfkHpyM_obCx4lphYrpC-kpU1a8oP5mAXlaNwlrcaGKGLSI0mEB4dRj5MDDxcaPMMLXFWydvlC1luqzme6L9R4qqoQyO9hMSEVsmn4Pp9y3G7QHo1wEmoelLO_Tn26YuYtmZ8',
      badge: 'pro' as const,
      stock: 80,
      stockQty: 80,
      stockLabel: '80% в наличии',
      stockLabelEn: '80% in stock',
      brand: 'ProConnect',
      category: 'electric',
      active: true,
    },
    {
      id: '2',
      name: 'Миксер строительный Bosch Professional 1200Вт',
      nameEn: 'Bosch Professional Mixer 1200W',
      price: 10990,
      oldPrice: 12800,
      image:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuBSQO5oTtCDmc2yca3QdSfTU6CPSrt7bU0ChV93tWMlTd46COUYYErjIAqDvOx3UVVAem3e4rjl7wkx8aQmyFuYrXVcJ9hU-k1Thhk-SD0HK6gchp6obRJyEZ5wYhOhdtZA_cm8FEATFQ5hIkbcoSglfkhJpSVNnsMimplRHW_zNSEv_y2e8hpM48BW3JNNU9cKS-a7CaQsb_cEdKUkePIIwn2Xi5B2yKtf4OkDKH6v9zDLF-P3fIpl79cW3WoW5SEkbEY8zuGin6HK',
      stock: 30,
      stockQty: 5,
      stockLabel: 'Осталось мало',
      stockLabelEn: 'Low stock',
      brand: 'Bosch',
      category: 'tools',
      active: true,
    },
    {
      id: '3',
      name: 'Сушилка для белья настенная складная SlimLine',
      nameEn: 'SlimLine Wall-mounted Drying Rack',
      price: 1450,
      oldPrice: 2100,
      image:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuCKWGRcwRKsX1cX_fvaYVna_gjjl4NK8ss-XSABvuMJSX19vst64NQvAvZ5NCYJJYUIT7OjTUyPAyKKdvAKy6DWYE8-aXYnO6ceObR9lqbwH_FrsfOmmu3pbJc2aRgpNh6_30Krm98-V7_D8tAQ-9PeLvEMC2VWmbuP_xn3hllbibNirGUjYM5C-jFZ6YoTnICyd63y58C51K_OMGNYWBXMWfCBVhDSL1U4ChHwX7kEDC80aq-zjaGJ1SG9gnK4saQvyX01NeC1E6Ll',
      stock: 50,
      stockQty: 50,
      stockLabel: 'В наличии',
      stockLabelEn: 'In stock',
      brand: 'SlimLine',
      category: 'plumbing',
      active: true,
    },
    {
      id: '4',
      name: 'Комплект инсталляции для подвесного унитаза',
      nameEn: 'Wall-hung Toilet Installation Kit',
      price: 8900,
      oldPrice: 11200,
      image:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuCUO2E_V-_nHfFL8AG1VE6aUbywldw3NoiIwUoCFyi0wi2R2nDRxp4NgQDiddtLrwgLgfqyBlyhlXK5h2hqjMq4i8SAbGTwMNCf81KET6dN5vHj0auYObALjFcDjYdZaA9HqcNi8QXGxN-bZn4GSS3_fEp7exH_xkc4IrhG_ZMXt_6d51LkpU3iSbePK6dA1KG6_o2uBHkV-kLCCfHCk2aFKO75PKfBtnXmj-XwNpr0QEom3K0suta37R633jsdk0zE4p--eRcD-bu4',
      badge: 'sale' as const,
      stock: 60,
      stockQty: 60,
      stockLabel: 'В наличии',
      stockLabelEn: 'In stock',
      brand: 'Grohe',
      category: 'plumbing',
      active: true,
    },
    {
      id: '5',
      name: 'Ударная дрель KM ATOM 18V',
      nameEn: 'KM ATOM 18V Impact Drill',
      price: 14990,
      oldPrice: 17990,
      image:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuDU7MTl_doAaH4mevNOAplZO7XkhHYv0aXgFupgTz_WFZjJDeOhX5y7IWnWkMrCsQSr1qRh6-xoqb6zGkA2s2tqAANNCGnCjak0sY75KT8jMjB34hTU6gf3RG1wgL-Gm0Q5v-BfKRyhxIhDJD_u21UOMUKwDhmYowOtUTx8S5GmmICY3kX0Oh4ZnGF524wHh_SHahC3TupwEajXknsbuz_4viRxv7ExnIqgE3f5F7UrfjKJYnlMr8eP4_Ef0UsrpT9HZ08Lh6LTpXlZ',
      badge: 'pro' as const,
      stock: 90,
      stockQty: 90,
      stockLabel: 'В наличии',
      stockLabelEn: 'In stock',
      brand: 'KM ATOM',
      category: 'tools',
      active: true,
    },
    {
      id: '6',
      name: 'Удлинитель силовой 25м',
      nameEn: '25m Power Extension Cord',
      price: 2990,
      image:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuAJrED_NNURGKwaCYtTokaxB3XkbaekjfUgbH0nJt5BoijwlK4IjCc6eCI3gVtr9xdQYfpBQSol713iAgSObQLssWpobjBtEgXFApFASO3IXMhwg_0m9oSPBiJyS8RrLwe_w3QREhX9cvynGEKbRlDdT6t3L19UXld6hRiQdThCxABmJL5kGzNfz9QNqfizxAtdgGrvMwh3_KDV1oECUAPV0xCwRBCzNz6pn4u8OJGqcfK9Zrd4lfvjKR64uVI0DdiyM6ytZjtmzqHa',
      stock: 70,
      stockQty: 70,
      stockLabel: 'В наличии',
      stockLabelEn: 'In stock',
      brand: 'ProConnect',
      category: 'electric',
      active: true,
    },
  ],
  services: [
    {
      id: 's1',
      icon: 'door_front',
      titleRu: 'Установка дверей',
      titleEn: 'Door installation',
      descRu: 'От замера до монтажа за 48 часов',
      descEn: 'From measurement to install in 48h',
      active: true,
    },
    {
      id: 's2',
      icon: 'calculate',
      titleRu: 'Калькулятор ремонта',
      titleEn: 'Renovation calculator',
      descRu: 'Рассчитайте смету за 5 минут',
      descEn: 'Estimate your budget in 5 minutes',
      active: true,
    },
    {
      id: 's3',
      icon: 'palette',
      titleRu: 'Колеровка краски',
      titleEn: 'Paint tinting',
      descRu: 'Более 15 000 оттенков в наличии',
      descEn: '15,000+ shades available',
      active: true,
    },
    {
      id: 's4',
      icon: 'local_shipping',
      titleRu: 'Доставка за 2 часа',
      titleEn: '2-hour delivery',
      descRu: 'Бесплатно при заказе от 30 000₽',
      descEn: 'Free for orders over 30,000₽',
      active: true,
    },
  ],
  promotions: [
    {
      id: 'p1',
      titleRu: 'Скидка 20% на первую закупку',
      titleEn: '20% off your first order',
      descriptionRu: 'Для новых клиентов BuildPro',
      descriptionEn: 'For new BuildPro customers',
      discountPercent: 20,
      type: 'promo' as const,
      startDate: '2024-01-01',
      endDate: '2026-12-31',
      active: true,
      productIds: [] as string[],
    },
    {
      id: 'p2',
      titleRu: 'Распродажа сантехники',
      titleEn: 'Plumbing clearance sale',
      descriptionRu: 'Скидки до 30% на Grohe и SlimLine',
      descriptionEn: 'Up to 30% off Grohe and SlimLine',
      discountPercent: 30,
      type: 'clearance' as const,
      startDate: '2024-06-01',
      endDate: '2026-12-31',
      active: true,
      productIds: ['3', '4'],
    },
  ],
  contentRu: {
    'nav.materials': 'Стройматериалы',
    'nav.tools': 'Инструмент',
    'nav.electric': 'Электрика',
    'nav.plumbing': 'Сантехника',
    'nav.garden': 'Сад',
    'nav.paint': 'Краски',
    'nav.promo': 'Акции',
    'nav.sale': 'Распродажа',
    'nav.catalog': 'Каталог',
    'nav.profile': 'Профиль',
    'nav.favorites': 'Избранное',
    'nav.cart': 'Корзина',
    'nav.home': 'Главная',
    'header.location': 'Санкт-Петербург',
    'header.phone': '8 800 555-35-35',
    'header.phoneHint': 'Круглосуточно',
    'header.searchPlaceholder': 'Поиск стройматериалов...',
    'header.find': 'Найти',
    'footer.tagline': 'Ваш надёжный партнёр в строительстве и ремонте.',
    'footer.newsletterHint': 'Промокод на 1000₽ для первого заказа',
    'home.heroTitle': 'Профессиональные материалы для вашего дома',
    'home.heroText': 'Высокое качество, проверенное экспертами BuildPro. Скидки до 20% на первую закупку.',
    'home.friendlyPrices': 'Дружеские цены',
    'home.servicesGrid': 'Сервисы и расчёты',
  },
  contentEn: {
    'nav.materials': 'Materials',
    'nav.tools': 'Tools',
    'nav.electric': 'Electrical',
    'nav.plumbing': 'Plumbing',
    'nav.garden': 'Garden',
    'nav.paint': 'Paint',
    'nav.promo': 'Promotions',
    'nav.sale': 'Sale',
    'nav.catalog': 'Catalog',
    'nav.profile': 'Profile',
    'nav.favorites': 'Favorites',
    'nav.cart': 'Cart',
    'nav.home': 'Home',
    'header.location': 'Saint Petersburg',
    'header.phone': '8 800 555-35-35',
    'header.phoneHint': '24/7',
    'header.searchPlaceholder': 'Search building materials...',
    'header.find': 'Search',
    'footer.tagline': 'Your reliable partner in construction and renovation.',
    'footer.newsletterHint': 'Get a 1000₽ promo code for your first order',
    'home.heroTitle': 'Professional materials for your home',
    'home.heroText': 'High quality verified by BuildPro experts. Up to 20% off your first purchase.',
    'home.friendlyPrices': 'Friendly prices',
    'home.servicesGrid': 'Services & calculators',
  },
};
